apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  labels:
    day: day3
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  local:
    path: /storage/day3/pv1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - radha
