apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2
  labels:
    day: day3
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  local:
    path: /storage/day3/pv2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - radha
