apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep4
  labels:
    day: day3
    sample: sample2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        day: day3
        sample: sample2
        layer: dep4
    spec:
      volumes:
        - name: vol1
          persistentVolumeClaim:
            claimName: pvc1
      containers:
        - name: c1
          image: nginx:alpine
          volumeMounts:
            - name: vol1
              mountPath: /data
  selector:
    matchLabels:
      day: day3
      sample: sample2
      layer: dep4
